// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package runtimeprofile

import (
	"bytes"
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/believems/filebeat-processors/impala_profile/thrift/impala/execstats"
	"github.com/believems/filebeat-processors/impala_profile/thrift/impala/metrics"
	"github.com/believems/filebeat-processors/impala_profile/thrift/impala/types"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = execstats.GoUnusedProtection__
var _ = metrics.GoUnusedProtection__
var _ = types.GoUnusedProtection__

func init() {
}
