name: Build Filebeat Processor
on:
  push:
    branches:
      - 'v*'
    tags:
      - 'v*'

jobs:
  build:
    name: "Build Filebeat"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Setup Golang"
        uses: actions/setup-go@v2
        with:
          stable: 'true'
      - name: "Build Processor"
        run: bash .compile.sh
