name: Build Filebeat Processors
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: "Build Filebeat"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Processors
        uses: actions/checkout@v2
        with:
          repository: 'ytpay/filebeat-processors'
          path: 'filebeat-processors'
          submodules: 'true'
      - name: Read Filebeat Version
        run: "echo FILEBEAT_VERSION=$(cat filebeat-version) >> $GITHUB_ENV"
        working-directory: ./filebeat-processors
      - name: Checkout Filebeat
        uses: actions/checkout@v2
        with:
          repository: 'elastic/beats'
          ref: "${{ env.FILEBEAT_VERSION }}"
          path: 'beats'
          submodules: 'true'
      - name: "Setup Golang"
        uses: actions/setup-go@v2
        with:
          stable: 'true'
      - name: "Install gox"
        working-directory: "${{ env.GITHUB_WORKSPACE }}"
        run: |
          go install github.com/mitchellh/gox@latest
      - name: "Build Processor"
        working-directory: ./beats
        run: |
          git checkout -b ${FILEBEAT_VERSION} ${FILEBEAT_VERSION}
          cat ../filebeat-processors/import.txt >> libbeat/cmd/instance/imports_common.go
          go get github.com/ytpay/filebeat-processors@${GITHUB_SHA}
          (cd filebeat && make crosscompile)
