name: Build Filebeat Processors
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: "Build Filebeat"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Processors
        uses: actions/checkout@v2
      - name: Read Filebeat Version
        run: "echo FILEBEAT_VERSION=$(cat filebeat-version) >> $GITHUB_ENV"
      - name: Checkout Filebeat
        uses: actions/checkout@v2
        with:
          repository: 'elastic/beats'
          ref: "$FILEBEAT_VERSION"
      - name: "Setup Golang"
        uses: actions/setup-go@v2
        with:
          stable: 'true'
      - name: "Build Processor"
        run: bash .compile.sh
