name: Build Filebeat Processors
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: "Build Filebeat"
    runs-on: ubuntu-latest
    env:
      GO111MODULE: 'on'
    steps:
      - name: Checkout Processors
        uses: actions/checkout@v3
        with:
          repository: 'believems/filebeat-processors'
          path: 'filebeat-processors'
          submodules: 'true'
      - name: Read Filebeat Version
        run: "echo FILEBEAT_VERSION=$(cat filebeat-version) >> ${GITHUB_ENV}"
        working-directory: ./filebeat-processors
      - name: Checkout Filebeat
        uses: actions/checkout@v3
        with:
          repository: 'elastic/beats'
          ref: "${{ env.FILEBEAT_VERSION }}"
          path: 'beats'
          submodules: 'true'
      - name: "Setup Golang"
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: "Install gox"
        working-directory: "${{ env.GITHUB_WORKSPACE }}"
        run: |
          go install github.com/mitchellh/gox@latest
      - name: "Build Processor"
        env:
          ACCESS_TOKEN: ${{ secrets.CI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
          GO111MODULE: on
          GOPRIVATE: github.com/believems/filebeat-processors
          GH_ACCESS_TOKEN: ${{ secrets.CI_TOKEN }}
        working-directory: ./beats
        run: |
          git checkout -b ${FILEBEAT_VERSION} ${FILEBEAT_VERSION}
          cat ../filebeat-processors/import.txt >> libbeat/cmd/instance/imports_common.go
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          go get github.com/believems/filebeat-processors@${GITHUB_SHA}
          go mod tidy
          sed -i  's/GOX_OS?=linux darwin windows freebsd netbsd openbsd/GOX_OS?=linux/' libbeat/scripts/Makefile
          (cd filebeat && make crosscompile && mv build/bin ${GITHUB_WORKSPACE}/artifacts)
          echo "ARTIFACTS_PATH=${GITHUB_WORKSPACE}/artifacts/*" >> ${GITHUB_ENV}
      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          name: "Bump ${{ env.FILEBEAT_VERSION }}"
          tag: "${{ env.FILEBEAT_VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "${{ env.ARTIFACTS_PATH }}"
          allowUpdates: 'true'
